
import streamlit as st

def render():
    st.markdown('''''')
    st.markdown('''## Análise de Clusterização de Candidatos''')
    st.markdown('''''')
    st.markdown('''Este relatório apresenta uma análise detalhada dos clusters obtidos a partir de um modelo de KMeans aplicado sobre perfis de candidatos. A clusterização considerou dados educacionais, experiência, presença de informações relevantes (como SAP e remuneração).''')
    st.markdown('''''')
    st.markdown('''---''')
    st.markdown('''''')

    # Cluster 0
    st.markdown('''### **Cluster 0 — "Exploradores Técnicos"**''')
    st.markdown('''''')
    st.markdown('''🧠 **Descrição**:  ''')
    st.markdown('''Candidatos com presença marcante na área de **Tecnologia da Informação**.  ''')
    st.markdown('''Apresentam nível hierárquico médio de especialista/consultor (3.26) e baixa média de escolaridade formal.  ''')
    st.markdown('''Apesar disso, possuem alguma experiência e perfil técnico.''')
    st.markdown('''''')
    st.markdown('''🏷️ **Área mais frequente**: Tecnologia da Informação  ''')
    st.markdown('''💰 **Remuneração**: 🔽 abaixo da média  ''')
    st.markdown('''💼 **Experiência (anos)**: 🔽 abaixo da média  ''')
    st.markdown('''📊 **Qtd. de experiências**: 🔽 abaixo da média  ''')
    st.markdown('''🧠 **Experiência com SAP**: 7%  ''')
    st.markdown('''''')
    st.markdown('''---''')
    st.markdown('''''')

    # Cluster 1
    st.markdown('''### **Cluster 1 — "Veteranos Invisíveis"**''')
    st.markdown('''''')
    st.markdown('''🧠 **Descrição**:  ''')
    st.markdown('''Profissionais com **boa formação educacional (3.15)** e hierarquia mais elevada.  ''')
    st.markdown('''Estão presentes principalmente na área **Jurídica**, e uma parte relevante tem experiência com SAP.  ''')
    st.markdown('''Apesar do bom perfil, apresentam comportamento reservado em remuneração e histórico profissional.''')
    st.markdown('''''')
    st.markdown('''🏷️ **Área mais frequente**: Jurídico  ''')
    st.markdown('''💰 **Remuneração**: 🔼 acima da média  ''')
    st.markdown('''💼 **Experiência (anos)**: 🔼 acima da média  ''')
    st.markdown('''📊 **Qtd. de experiências**: 🔼 acima da média  ''')
    st.markdown('''🧠 **Experiência com SAP**: 31%  ''')
    st.markdown('''''')
    st.markdown('''---''')
    st.markdown('''''')

    # Cluster 2
    st.markdown('''### **Cluster 2 — "Sombras do Cadastro"**''')
    st.markdown('''''')
    st.markdown('''🧠 **Descrição**:  ''')
    st.markdown('''Candidatos com baixíssimo nível educacional (média ≈ 0) e pouco histórico profissional.  ''')
    st.markdown('''Grande parte pertence à área Jurídica, o que pode ser ruído nos dados.  ''')
    st.markdown('''Possuem baixa hierarquia e menor participação em SAP ou experiência sólida.''')
    st.markdown('''''')
    st.markdown('''🏷️ **Área mais frequente**: Jurídico  ''')
    st.markdown('''💰 **Remuneração**: 🔽 abaixo da média  ''')
    st.markdown('''💼 **Experiência (anos)**: 🔽 abaixo da média  ''')
    st.markdown('''📊 **Qtd. de experiências**: 🔽 abaixo da média  ''')
    st.markdown('''🧠 **Experiência com SAP**: 14%  ''')
    st.markdown('''''')
    st.markdown('''---''')
    st.markdown('''''')

    # Cluster 3
    st.markdown('''### **Cluster 3 — "Especialistas Aspiracionais"**''')
    st.markdown('''''')
    st.markdown('''🧠 **Descrição**:  ''')
    st.markdown('''Grupo qualificado, com média de escolaridade de **pós-graduação** (3.24) e forte presença na área de TI.  ''')
    st.markdown('''Mostram bom nível hierárquico (3.11) e experiência relevante, incluindo boa participação em SAP.  ''')
    st.markdown('''São candidatos mais preparados para liderança e crescimento.''')
    st.markdown('''''')
    st.markdown('''🏷️ **Área mais frequente**: Tecnologia da Informação  ''')
    st.markdown('''💰 **Remuneração**: 🔼 acima da média  ''')
    st.markdown('''💼 **Experiência (anos)**: 🔼 acima da média  ''')
    st.markdown('''📊 **Qtd. de experiências**: 🔼 acima da média  ''')
    st.markdown('''🧠 **Experiência com SAP**: 29%  ''')
    st.markdown('''''')
    st.markdown('''---''')
    st.markdown('''''')

    st.markdown('''### Considerações Finais:''')
    st.markdown('''''')
    st.markdown('''A clusterização permitiu identificar perfis distintos — desde candidatos altamente qualificados até registros quase vazios. Os dados podem apoiar campanhas de recrutamento, estratégias de qualificação e decisões de negócio em RH.''')
